### ISSUE TITLE
The currently selected item is not displayed

### ISSUE THREAD

**Issue by Q0** [euyogi/Tema-YogiAmoled#3]
Hi! Theme is cool, but I met an unpleasant moment:

When a hint appears if you select items, the selection of the element disappears and it is not clear what you are choosing.

https://github.com/euyogi/Tema-YogiAmoled/assets/15221660/3a2dffb9-e897-4151-9797-9a115c41e756

PhpStorm 2024.1

**Comment by euyogi** [comment]
thanks for the issue. It should be fixed now. Update will come officially through jetbrains in 2-3 business days, but if you want you can download the .jar in the repository page.
![image](https://github.com/euyogi/Tema-YogiAmoled/assets/46427886/3d2d6fc2-141d-4d05-8c99-a5da5ff2c9fd)
